CREATE TABLE `customization` (
	`id` integer PRIMARY KEY NOT NULL,
	`site_name` text DEFAULT 'Torqen Cloud' NOT NULL,
	`logo_url` text DEFAULT '/Logo-dark.png' NOT NULL,
	`brand_color` text DEFAULT '#18181b' NOT NULL,
	`brand_color_dark` text DEFAULT '#ffffff' NOT NULL,
	`brand_hover` text DEFAULT '#27272a' NOT NULL,
	`brand_hover_dark` text DEFAULT '#f4f4f5' NOT NULL,
	`surface` text DEFAULT '#ffffff' NOT NULL,
	`surface_dark` text DEFAULT '#121212' NOT NULL,
	`surface_light` text DEFAULT '#f4f4f5' NOT NULL,
	`surface_light_dark` text DEFAULT '#18181b' NOT NULL,
	`surface_highlight` text DEFAULT '#e5e5e5' NOT NULL,
	`surface_highlight_dark` text DEFAULT '#27272a' NOT NULL,
	`surface_lighter` text DEFAULT '#e4e4e7' NOT NULL,
	`surface_lighter_dark` text DEFAULT '#3f3f46' NOT NULL,
	`muted_foreground` text DEFAULT '#71717a' NOT NULL,
	`muted_foreground_dark` text DEFAULT '#a1a1aa' NOT NULL,
	`border_color` text DEFAULT '#e4e4e7' NOT NULL,
	`border_color_dark` text DEFAULT '#3f3f46' NOT NULL,
	`border_radius` text DEFAULT '6px' NOT NULL,
	`font_family` text DEFAULT 'Inter' NOT NULL,
	`is_compact` integer DEFAULT true NOT NULL,
	`is_dark` integer DEFAULT true NOT NULL,
	`updated_at` integer NOT NULL
);
